routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index')->name('home');
//Route::get('/home', 'ProductWishlistController@array');
Route::get('/my-account', 'AccountController@index')->name('my-account');
Route::post('/my-account/details', 'AccountController@postAccount')->name('account.details');
Route::post('/my-account/passwords', 'AccountController@changePassword')->name('account.passwords');

Auth::routes();
Route::post('/my-account', 'Auth\RegisterController@register')->name('register');

Route::resource('product', 'ProductController');
Route::get('collections/{category}', 'ProductController@collections')->name('collections.index');
Route::get('collections', 'CategoryController@listening')->name('collections');
Route::get('products/category/{category}', 'ProductController@listeningCategories')->name('listening.products.categories');

Route::get('/admin', 'Admin\AdminController@index')->name('admin');
Route::resource('image-product', 'Admin\ImageProductController');
Route::resource('category', 'CategoryController');

Route::get('colors-sizes-product/create/{product}', 'Admin\ColorSizeProductController@create')->name('colors-sizes.create');
Route::post('colors-sizes-product/create/{product}', 'Admin\ColorSizeProductController@store')->name('colors-sizes.store');
Route::get('colors-sizes-product/create/{product}/edit/{colorSizeProduct}', 'Admin\ColorSizeProductController@edit')->name('colors-sizes.edit');
Route::put('colors-sizes-product/create/{product}/edit/{colorSizeProduct}', 'Admin\ColorSizeProductController@update')->name('colors-sizes.update');

/*
Route::get('product-filter/{slug}', 'ProductFilterController@category')->name('product-filter.category');
Route::get('product-filter/filter/clear', 'ProductFilterController@clear')->name('product-filter.clear');
Route::get('product-filter/filter/clear/{filter}', 'ProductFilterController@clearByFilter')->name('product-filter.clear.filter');
Route::get('product-filter/filter/{index}', 'ProductFilterController@page')->name('product-filter.page');
Route::get('product-filter/filter/size/{size}', 'ProductFilterController@size')->name('product-filter.size');
Route::get('product-filter/filter/color/{color}', 'ProductFilterController@color')->name('product-filter.color');
Route::get('product-filter/filter/price/{min}/{max}', 'ProductFilterController@price')
    ->where(['min' => '[0-9]+', 'max' => '[0-9]+'])
    ->name('product-filter.price');

Route::get('product-filter/filter/selected/popularity', 'ProductFilterController@popularity')->name('product-filter.popularity');
Route::get('product-filter/filter/selected/date', 'ProductFilterController@date')->name('product-filter.date');
Route::get('product-filter/filter/selected/price-asc', 'ProductFilterController@priceAsc')->name('product-filter.price-asc');
Route::get('product-filter/filter/selected/price-desc', 'ProductFilterController@priceDesc')->name('product-filter.price-desc');
*/

/* Routes Basket And Wishlist */
Route::resource('products/wishlist', 'ProductWishlistController')->names('product.wishlist');
Route::resource('products/basket', 'BasketProductController')->names('product.basket');
Route::get('products/session/basket', 'SessionBasketController@basket')->name('product.basket.session');
Route::put('products/session/basket/update', 'SessionBasketController@update')->name('product.basket.update.session');

Route::post('product/wishlist/add', 'ProductWishlistController@add')->name('product.wishlist.add');
Route::get('product/basket/load', 'BasketProductController@loadProductsBasket')->name('product.basket.load');
Route::delete('product/basket/delete/{basketsProduct}', 'BasketProductController@delete')->name('product.basket.delete');
Route::delete('product/wishlist/delete/{wishlistsProductID}', 'ProductWishlistController@delete')->name('product.wishlist.delete');

/* Routes Checkout */
Route::get('checkout', 'BasketController@checkout')->name('checkout');
Route::post('checkout/cart', 'CheckoutController@store')->name('checkout.store');
Route::post('checkout/customer', 'CheckoutController@createCustomer')->name('checkout.customer');

/* Payment Paypal */
Route::post('payment/paypal', 'PaypalPaymentController@index')->name('paypal.payment');
Route::post('payment/paypal/sale', 'PaypalPaymentController@payment')->name('paypal.payment.sale');

Route::post('products/search', 'ProductController@search')->name('search');
Route::get('products/search/{search}', 'ProductController@searchGET')->name('search.products');
Route::get('contact', 'ContactController@contact')->name('contact');
Route::post('contact/post', 'ContactController@post')->name('contact.post');

/* Routes Products */
Route::get('admin/products', 'ProductController@listening')->name('listening.products');

/* Routes Orders And Customers */
Route::resource('/admin/orders', 'OrderController')->names('orders');
Route::resource('/admin/customers', 'CustomerController')->names('customers');

/* Routes Orders And Customers for Paypal */
Route::resource('/admin/paypal/orders', 'OrderPaypalController')->names('orders.paypal');
Route::resource('/admin/paypal/customers', 'CustomerPaypalController')->names('customers.paypal');

/* Invoice Orders */
Route::get('/invoice/{order}', 'OrderController@invoice')->name('invoice.order');
Route::get('/invoice/paypal/{order}', 'OrderPaypalController@invoice')->name('invoice.paypal.order');
/* Livraison/Retour Routes */
Route::get('/delivery', 'Pages\DeliveryController@index')->name('delivery');

/* ROUTES PAGES */
Route::get('/CGV', 'Pages\PageController@CGV')->name('CGV');

/* Concept Routes */
Route::get('/concept', 'Pages\ConceptController@index')->name('concept');
/* PAGE 404 Routes */
Route::get('/404', 'Pages\PageController@errorCode404')->name('404');

app/Order.php
<?php

namespace App;

use App\src\helpers\Stripe;
use Carbon\Carbon;
use Carbon\CarbonInterface;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Stripe\Exception\ApiErrorException;

class Order extends Model
{

    public $timestamps = true;

    protected $guarded = [];
    /**
     * @var Stripe
     */
    private static Stripe $stripe;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        self::$stripe = new Stripe();
    }

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @param Collection $orders
     * @return int
     */
    public static function countProducts(Collection $orders): int
    {
        $newData = [];
        foreach ($orders as $order) {
            $products = $order['products'] ?: [];
            foreach ($products as $key => $product) {
                $newData[] = $product;
            }
        }
        return count($newData + OrderPaypal::countProducts());
    }

    /**
     * @param $query
     * @param int $userID
     * @return Builder
     */
    public function scopeFindUserLast($query, int $userID): Builder
    {
        return $query->where('user_id', $userID)->orderBy('created_at', 'DESC');
    }

    /**
     * @param $value
     * @return array
     */
    public function getProductsAttribute($value): array
    {
        return unserialize($value);
    }

    /**
     * @return string
     */
    public function getCreatedAt(): string
    {
        return Carbon::make($this->created_at)->format('F j, Y');
    }

    /**
     * @param $value
     * @return string
     */
    public function getPaymentIndentCreatedAttribute($value): string
    {
        return Carbon::parse($value)->format('d M, Y');
    }

    /**
     * @param $value
     * @return float|int
     */
    public function getAmountAttribute($value)
    {
        return ($value / 100);
    }

    /**
     * @param Order $order
     * @return string|null
     * @throws ApiErrorException
     */
    public static function getName(Order $order): ?string
    {
        $paymentIntent = self::$stripe->getPaymentIntent($order->payment_indent_id);
        $customer = self::$stripe->getCustomer($paymentIntent->customer);

        return $customer->name;
    }

    /**
     * @return Stripe
     */
    private static function getStripe(): Stripe
    {
        return self::$stripe;
    }

    /**
     * @param $query
     * @return mixed
     */
    public function scopeLast($query)
    {
        return $query->orderBy('created_at', 'desc');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Forms\EditTrackingOrderForm;
use App\Order;
use App\src\helpers\ConvertPdf;
use App\src\helpers\Price;
use App\src\helpers\Stripe;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\View\View;
use Kris\LaravelFormBuilder\FormBuilder;
use Spipu\Html2Pdf\Html2Pdf;
use Stripe\Exception\ApiErrorException;

class OrderController extends Controller
{
    /**
     * @var Stripe
     */
    private Stripe $stripe;
    /**
     * @var FormBuilder
     */
    private FormBuilder $formBuilder;

    /**
     * OrderController constructor.
     * @param FormBuilder $formBuilder
     */
    public function __construct(FormBuilder $formBuilder)
    {
        $this->stripe = new Stripe();
        $this->formBuilder = $formBuilder;
    }

    /**
     * Display a listing of the resource.
     * @return Application|Factory|View
     */
    public function index()
    {
        $orders = Order::paginate(10);
        $page = 'admin/orders';
        return view('orders.index', compact('orders', 'page'));
    }

    /**
     * @param Request $request
     * @param Order $order
     * @return void
     * @throws ApiErrorException
     */
    public function invoice(Request $request, Order $order)
    {
        $html2Pdf = new Html2Pdf();
        $convert = new ConvertPdf($html2Pdf);

        $file = $request->server->get('DOCUMENT_ROOT') . '/img/icons/logo-text.jpg';

        $payment = $this->stripe->getPaymentIntent($order->payment_indent_id);
        $customer = $this->stripe->getCustomer($payment->customer);
        $paymentMethod = $this->stripe->getPaymentMethod($payment->payment_method)->card;
        $priceTotal = Price::addTotal($order['products']);
        return $convert->pdf($order, $file, $customer, $paymentMethod, $priceTotal);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Order $order
     * @return Application|Factory|View|void
     */
    public function edit(Order $order)
    {
        $trackingOrder = $order->tracking_order ?: null;
        $form = $this->formBuilder->create(EditTrackingOrderForm::class, [
            'method' => 'PUT',
            'url' => route('orders.update', [$order]),
            'data' => ['tracking_order' => $trackingOrder]
        ]);
        return view('orders.edit', compact('form'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param Order $order
     * @return RedirectResponse
     */
    public function update(Request $request, Order $order): RedirectResponse
    {
        $updated = $order->update($request->all());
        if (!$updated) {
            return redirect()
                ->route('orders.index')
                ->with('messageError', 'An error has occurred !');
        }
        return redirect()
            ->route('orders.index')
            ->with('message', 'You are updated your tracking order with success !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/template/admin/orders/table-orders-paypal.blade.php
<table class="table table-centered table-nowrap mb-0">
    <thead class="thead-light">
    <tr>
        <th>Order ID</th>
        <th>Billing Name</th>
        <th>Date</th>
        <th>Total</th>
        <th>Payment Status</th>
        <th>Tracking Order</th>
        <th>Payment Method</th>
        @if ($page !== 'admin')
            <th>View Details</th>
        @endif
    </tr>
    </thead>
    <tbody>
    @foreach($ordersPaypal as $order)
        <tr>
            <td>
                <a href="#" class="text-body font-weight-bold">#SK{{ $order['id'] }}</a>
            </td>
            <td>{{ \App\OrderPaypal::getName($order) }}</td>
            <td>{{ $order->created_at }}</td>
            <td>{{ $order->amount }}€</td>
            <td>
                <span class="badge badge-pill badge-soft-success font-size-12">Paid</span>
            </td>
            <td>
                @if ($order->tracking_order)
                    @if ($order->tracking_order === 'en cours de traitement')
                        <span
                            class="badge badge-pill badge-warning font-size-12">{{ ucfirst($order->tracking_order) }}</span>
                    @elseif($order->tracking_order === 'envoyer')
                        <span
                            class="badge badge-pill badge-primary font-size-12">{{ ucfirst($order->tracking_order) }}</span>
                    @elseif($order->tracking_order === 'reçu')
                        <span
                            class="badge badge-pill badge-soft-success font-size-12">{{ ucfirst($order->tracking_order) }}</span>
                    @endif
                @else
                    <span
                        class="badge badge-pill badge-danger font-size-12">Echec de l'envoi</span>
                @endif
            </td>
            <td>
                <i class="fa fa-cc-paypal mr-1 font-size-14"></i>
                {{ ucfirst('paypal') }}
            </td>
            @if ($page !== 'admin')
                <td>
                    <button type="button" class="btn btn-sm btn-rounded effect-click-btn btn-primary btn-submit-primary"
                            data-toggle="modal" data-target=".order-products-{{ $order['id'] }}">View Details
                    </button>
                    <a href="{{ route('orders.paypal.edit', [$order->id]) }}"
                       class="btn btn-sm btn-rounded effect-click-btn btn-success btn-submit-success">Update
                        tracking</a>
                </td>
            @endif
        </tr>
    @endforeach
    </tbody>
</table>
@include('orders.modal', ['orders' => $ordersPaypal])

resources/views/template/admin/orders/table-orders.blade.php
<table class="table table-centered table-nowrap mb-0">
    <thead class="thead-light">
    <tr>
        <th>Order ID</th>
        <th>Billing Name</th>
        <th>Date</th>
        <th>Total</th>
        <th>Payment Status</th>
        <th>Tracking Control</th>
        <th>Payment Method</th>
        @if ($page !== 'admin')
            <th>View Details</th>
        @endif
    </tr>
    </thead>
    <tbody>
    @foreach($orders as $order)
        <tr>
            <td>
                <a href="#" class="text-body font-weight-bold">#SK{{ $order['id'] }}</a>
            </td>
            <td>{{ \App\Order::getName($order) }}</td>
            <td>{{ $order->payment_indent_created }}</td>
            <td>{{ $order->amount }}€</td>
            <td>
                <span class="badge badge-pill badge-soft-success font-size-12">Paid</span>
            </td>
            <td>
                @if ($order->tracking_order)
                    @if ($order->tracking_order === 'en cours de traitement')
                        <span
                            class="badge badge-pill badge-warning font-size-12">{{ ucfirst($order->tracking_order) }}</span>
                    @elseif($order->tracking_order === 'envoyer')
                        <span
                            class="badge badge-pill badge-primary font-size-12">{{ ucfirst($order->tracking_order) }}</span>
                    @elseif($order->tracking_order === 'reçu')
                        <span
                            class="badge badge-pill badge-soft-success font-size-12">{{ ucfirst($order->tracking_order) }}</span>
                    @endif
                @else
                    <span
                        class="badge badge-pill badge-danger font-size-12">Echec de l'envoi</span>
                @endif
            </td>
            <td>
                <i class="fa fa-cc-{{ $order->payment_method }} mr-1 font-size-14"></i>
                {{ ucfirst( $order->payment_method) }}
            </td>
            @if ($page !== 'admin')
                <td>
                    <button type="button" class="btn btn-sm btn-rounded effect-click-btn btn-primary btn-submit-primary"
                            data-toggle="modal" data-target=".order-products-{{ $order['id'] }}">View Details
                    </button>
                    <a href="{{ route('orders.edit', [$order]) }}"
                       class="btn btn-sm btn-rounded effect-click-btn btn-success btn-submit-success">Update
                        tracking</a>
                </td>
            @endif
        </tr>
    @endforeach
    </tbody>
</table>
@include('orders.modal', [$orders])